version: '3'
services:
  master:
    build:
      context: ./master
    networks: 
      default:
        ipv4_address: 172.16.0.2
    privileged: true
  slave:
    build:
      context: ./slave
    networks: 
      default:
        ipv4_address: 172.16.0.3
    privileged: true
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  172.16.0.0/24
